# Generated by Django 5.0.3 on 2024-03-14 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0003_alter_place_place_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="floor",
            name="map",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="floors",
                to="maps.map",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="floor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="places",
                to="maps.floor",
            ),
        ),
    ]
